# Generated by Django 5.0.6 on 2024-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=-1, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
